# Generated by Django 4.0.4 on 2022-04-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_profile_photo_user_photo_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Abidjan', 'Abidjan'), ('Bouaké', 'Bouaké'), ('San-Pédro', 'San-Pédro'), ('Korhogo', 'Korhogo'), ('Abengouro', 'Abengouro'), ('Man', 'Man'), ('Abengouro', 'Abengouro'), ('Daloa', 'Daloa'), ('Agboville', 'Agboville'), ('Bingerville', 'Bingerville')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ad', models.CharField(max_length=30)),
                ('description_ad', models.CharField(max_length=1000)),
                ('price_ad', models.IntegerField()),
                ('phto_add', models.ImageField(upload_to='')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.city')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.house')),
            ],
        ),
    ]
