# Generated by Django 4.0.4 on 2022-05-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_city_house_postad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postad',
            name='city',
        ),
        migrations.RemoveField(
            model_name='postad',
            name='house',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='House',
        ),
        migrations.DeleteModel(
            name='PostAd',
        ),
    ]
