# Generated by Django 4.0.4 on 2022-05-01 01:37

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ad', models.CharField(max_length=30)),
                ('description_ad', models.CharField(max_length=1000)),
                ('price_ad', models.IntegerField()),
                ('photo_ad', models.ImageField(upload_to='', validators=[django.core.validators.MinValueValidator(0)])),
                ('date_create_ad', models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 1, 1, 37, 13, 408221, tzinfo=utc), verbose_name='Date création')),
                ('date_modified_ad', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_ad.city')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_ad.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
