# Generated by Django 4.0.4 on 2022-05-01 01:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='date_create_ad',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 1, 1, 37, 18, 1659, tzinfo=utc), verbose_name='Date création'),
        ),
    ]
