# Generated by Django 4.0.4 on 2022-05-01 01:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_ad', '0002_alter_postad_date_create_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='date_create_ad',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 1, 1, 40, 30, 546869, tzinfo=utc), verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='postad',
            name='description_ad',
            field=models.TextField(max_length=1000),
        ),
    ]
