# Generated by Django 4.0.4 on 2022-05-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post_ad', '0002_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='postad',
            name='district',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='post_ad.district'),
            preserve_default=False,
        ),
    ]
