# Generated by Django 4.0.4 on 2022-05-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_ad', '0003_postad_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postad',
            name='user_id_ad',
        ),
    ]
