# Generated by Django 4.0.4 on 2022-05-01 03:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_ad', '0004_alter_postad_date_create_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postad',
            name='photo_ad',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='postad',
            name='price_ad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
