# Generated by Django 4.0.4 on 2022-05-06 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_ad', '0005_postad_number_of_piece_searchproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='postad',
            name='number_phone',
            field=models.IntegerField(default=1020304056, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postad',
            name='estate_type',
            field=models.CharField(choices=[('Location', 'Renting'), ('Vente', 'Purchasing')], max_length=25),
        ),
    ]
