# Generated by Django 4.0.4 on 2022-05-01 14:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_ad', '0005_alter_postad_photo_ad_alter_postad_price_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postad',
            name='date_modified_ad',
        ),
        migrations.AlterField(
            model_name='postad',
            name='date_create_ad',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postad',
            name='price_ad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)]),
        ),
    ]
