# Generated by Django 4.0.4 on 2022-05-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_ad', '0006_remove_postad_date_modified_ad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postad',
            name='user',
        ),
    ]
