# Generated by Django 4.0.4 on 2022-05-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_ad', '0007_remove_postad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postad',
            name='user',
            field=models.CharField(default='inconnue', max_length=150),
            preserve_default=False,
        ),
    ]
