# Generated by Django 4.0.4 on 2022-05-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_ad', '0008_postad_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postad',
            name='estate_type',
            field=models.CharField(choices=[('Location', 'renting'), ('Vente', 'purchasing')], default='Location', max_length=25),
            preserve_default=False,
        ),
    ]
