# Generated by Django 4.0.4 on 2022-05-03 00:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_ad', '0009_postad_estate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postad',
            name='user_id_ad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000000)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postad',
            name='estate_type',
            field=models.CharField(choices=[('Location', 'Renting'), ('Vente', 'Purchasing')], max_length=25),
        ),
    ]
